config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :pointers

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root :to => "home#index"

  get 'map' => 'home#map', :as => 'map'
  get 'list' => 'pointers#list', :as => 'list'
  get '/dynamic_content' => 'pointers#dynamic_content'
  get '/search' => 'home#search'

  get '/parse' => 'pointers#parse', :as => 'parse'
  get 'home/full_desc' => 'home#full_desc'
  get '/my_places' => 'home#my_places'
  get '/get_direction_info' => 'home#get_direction_info'
  get 'show_pointer_on_map/:id' => 'pointers#show_pointer_on_map', :as => 'show_pointer_on_map'
  get 'create_visit/:id' => 'desires#create_visit'
  get 'set_visited/:id' => 'desires#set_visited'
  get 'options' => 'home#options'

  post 'import_ratings' => 'pointers#import_ratings', defaults: {format: :json}
end

app/controllers/home_controller.rb
include MapMethods

class HomeController < ApplicationController
  #@@resc_arr =[]
  #before_action proc { @@resc_arr =[] }, :except => [:all_list]

  def index
    @last_points = Pointer.limit(10).order("rec_date DESC, id ASC")
    @top_points = Pointer.limit(10).order("rating DESC, rec_date DESC, id ASC")
    gon.markers = Pointer.all.map { |p| { lat: p.latitude, lng: p.longitude, desc: p.description } }
  end

  def map
    user_id = current_user.blank? ? 0 : current_user.id
    stat = params[:stat]
    my = params[:my] == '1'

    if params[:q].blank?
      pointers = Pointer.select_pointers_by_user(user_id, my, stat)
    else
      q = params[:q]
      pointers = Pointer.where { full_desc =~ "%#{q}%" }
      #pointers = Pointer.find_by_sql("SELECT pointers.id, pointers.latitude, pointers.longitude, pointers.description, pointers.full_desc, desires.stat
      #                              FROM pointers
      #                              LEFT OUTER JOIN desires
      #                              ON pointers.id = desires.pointer_id AND desires.user_id = #{user_id}
      #                              where pointers.full_desc LIKE '%#{q}%'")
      @q = q
    end

    @size = pointers.size
    @zoom = params[:zoom] ? params[:zoom] : 9

    respond_to do |format|
      format.html do
        @json = build_map(pointers)
      end
      format.mobile
      format.js do
        unless params.has_key?(:from) || params.has_key?(:to)
          @json = build_map(pointers)
        else
          render nothing: true
        end
      end
    end
  end

  def full_desc
    id = params[:id]
    @desc = (Pointer.find(id).full_desc).delete("\r")

    respond_to do |format|
      format.js { render :layout => false }
    end
  end

  def search
    user_id = current_user.blank? ? 0 : current_user.id

    if params[:q].blank?
      @q = ""
      pointers = Pointer.all
    else
      q = params[:q]

      unless params.has_key?(:slider) && params[:slider] == "slider"
        render :js => "window.location.href = '#{map_url(:q => q)}'"
        return
      end

      pointers = Pointer.where { full_desc =~ "%#{q}%" }

      #pointers = Pointer.find_by_sql("SELECT pointers.id, pointers.latitude, pointers.longitude, pointers.description, pointers.full_desc, desires.stat
      #                              FROM pointers
      #                              LEFT OUTER JOIN desires
      #                              ON pointers.id = desires.pointer_id AND desires.user_id = #{user_id}
      #                              where pointers.full_desc LIKE '%#{q}%'")
      @q = q
    end

    @size = pointers.size
    @json = build_map(pointers)

    respond_to do |format|
      format.js { render :layout => false }
    end
  end

  def get_direction_info
    @from = params[:from]
    @to = params[:to]
    render :layout => false
  end

  def options

  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_pointers.html.haml
- @index = 0 if @index.nil?
- @pointers.each_with_index do |elem, index|
  .well
    -#.numb
      = @index + index + 1
    .full_desc{:style => "margin-bottom: 5px;"}
      = elem.full_desc
      = link_to "More...", pointer_path(elem)
    -#.coord
      "#{elem.latitude}, #{elem.longitude}"

app/views/home/_pointers.mobile.haml
- @index = 0 if @index.nil?
- @pointers.each_with_index do |elem, index|
  -#%li
    %a{"href" => "#"}
      = elem.full_desc


  %div{"data-role" => "collapsible"}
    %h3
      = elem.description
    %p
      = elem.full_desc
    %a{"data-role"=>"button", "href"=>"#", "data-icon"=>"star", "data-iconpos"=>"right"}
      Show on map

app/views/home/all_list.html.haml
= javascript_include_tag 'jquery.scrollExtend'

:javascript
  var index = 1
  jQuery(document).ready(
    function() {
    //
    //
    }

  );

  $(window).scroll(
  function()
  {

    var fire = $("#hid_inp").attr("value");
    var add_pointers = $("#add_pointers").attr("value");

      if ((document.body.scrollHeight - $(this).scrollTop()  > $(this).height()) && (fire == "1"))
      {
        fire = "0";
      };

      if ((document.body.scrollHeight - $(this).scrollTop()  <= $(this).height()) && (fire == "0") && (add_pointers == "1"))
      {
          index = index + 1;

          $.get("/dynamic_content?index="+index,
            function(data) {
              data;
          });
          fire = "1";
      };
      $("#hid_inp").attr("value", fire);
  });

-#= @resc_arr.size
-#= @pointers.size

%input{:id=>"add_pointers", :type => "hidden", :value => "1"}
%input{:id=>"hid_inp", :type => "hidden", :value => "0"}

.row
  .span12
    %p
      Number of points:
      = @all_pointers.size
.row
  .span12
    .scroll_container
      = render :partial => 'pointers'

app/views/home/all_list.mobile.haml
:javascript
  var index = 1

  $(window).scroll(
  function()
  {
    var fire = $("#hid_inp").attr("value");
    var add_pointers = $("#add_pointers").attr("value");

      if (($(window).scrollTop() > 1 && (($(window).scrollTop() + $(window).height()) / $(document).height()) < 0.75) && (fire == "1"))
      {
        fire = "0";
      };

      if (($(window).scrollTop() == 0 && add_pointers == 1) || ($(window).scrollTop() > 1 && (($(window).scrollTop() + $(window).height()) / $(document).height()) > 0.75) && (fire == "0"))
        {
          $.mobile.loading( 'show' )
          $.get("/dynamic_content?index="+index,
            function(data) {
              data;
          });

          fire = "1";
          index = index + 1;
        };
      $("#hid_inp").attr("value", fire);
      $("#add_pointers").attr("value", index);
  });

-#= @resc_arr.size
-#= @pointers.size

-#=======header===============
- content_for :header do
  %div{"data-role" => "header", "data-theme" => "a", "data-position" => "fixed"}
    %a.ui-btn-left{"data-icon" => "arrow-l", "data-iconpos" => "left", "data-role" => "button", :href => "/", "data-transition" => "slide", "data-direction" => "reverse"}
      Home
    %h3
      List of Places

-#=======content===============

%input{:id=>"add_pointers", :type => "hidden", :value => "1"}
%input{:id=>"hid_inp", :type => "hidden", :value => "0"}

-#%ul{"data-role" => "listview", "id" => "scroll_container"}
-#  = render :partial => 'pointers'

%div{"data-role" => "collapsible-set", "id" => "scroll_container"}
  = render :partial => 'pointers'

-#.row
  .span12
    %p
      Number of points:
      = @all_pointers.size

app/views/home/full_desc.js.erb
show_panel(0);
$(".well.description").html("<%=@desc%>");

app/views/home/get_direction.html.haml
-#= Gmaps4rails.destination({"from" => "48.5897,23.1138", "to" => "48.5374,23.6524"},{"language"  => "ru","mode"      => "DRIVING","avoid"     => ["tolls", "highways"], "language"  => "ru" }, "pretty" )

-#= gmaps({"direction"   => { "data" => { "from" => "#{@ride.latitude},#{@ride.longitude}", "to" => "#{@ride.spot.latitude},#{@ride.spot.longitude}" } }})
= gmaps({"direction"   => { "data" => { "from" => "48.5897,23.1138", "to" => "48.5374,23.6524" } }})
-#= gmaps({ :direction => {:data => { :from => @map.origin, :to => @map.destination}}})

app/views/home/get_direction_info.js.erb
var directionsDisplay;
var directionsService = new google.maps.DirectionsService();
var from = [<%= @from.split(",")[0].to_f %>, <%= @from.split(",")[1].to_f %>];
var to = [<%= @to.split(",")[0].to_f %>, <%= @to.split(",")[1].to_f %>];

directionsDisplay = new google.maps.DirectionsRenderer();
//Gmaps.map.replaceMarkers({});
window.mapHandler.clusterer.clear();
directionsDisplay.setMap(window.mapHandler.getMap());
directionsDisplay.setPanel(document.getElementById('directions-panel'));

var start = new google.maps.LatLng(from[0], from[1]);
var end = new google.maps.LatLng(to[0], to[1]);
var request = {
    origin: start,
    destination: end,
    travelMode: google.maps.TravelMode.DRIVING
};
directionsService.route(request, function (result, status) {
    if (status == google.maps.DirectionsStatus.OK) {
        directionsDisplay.setDirections(result);
    }
});

app/views/home/index.html.haml
.row
  .list-widget
    .list-head
      %h3
        10 Last added places
    %ul
      - @last_points.each do |point|
        %li
          %i.fav{:style => "background-image:url('https://www.google.com/s2/u/0/favicons?domain=www.lukew.com');"}
          %div
            %a{:href => "#{show_pointer_on_map_path(point.id)}"}
              = point.description

      %li
        %a.list-view{:href => "/list"} View all

  .list-widget
    .list-head
      %h3
        10 Most popular places
    %ul
      - @top_points.each do |point|
        %li
          %i.fav{:style => "background-image:url('https://www.google.com/s2/u/0/favicons?domain=www.lukew.com');"}
          %div
            %a{:href => "#{show_pointer_on_map_path(point.id)}"}
              = point.description

      %li
        %a.list-view{:href => "/list"} View all

.row
  #footer{:style => "text-align: center;"}
    %p
      All data are taken from
      %a{:href => "http://poi.uzhgorod.ua/"}
        poi.uzhgorod.ua
    %p
      © 2014
      %a{:href => 'https://github.com/slaw-ik'} Miroslav Nastenko

app/views/home/index.mobile.haml
-#=======header===============
- content_for :header do
  %div{"data-role" => "header", "data-theme" => "a"}
    %h3
      Places of Transcarpathian

-#=======content===============
%div{"data-role" => "collapsible-set"}
  %div{"data-role" => "collapsible"}
    %h3
      10 Last added Places
    %ul{"data-divider-theme" => "b", "data-inset" => "true", "data-role" => "listview", "data-mini" => "true"}
      - @last_points.each do |point|
        %li{"data-theme" => "c"}
          %a{"data-transition" => "slide", :href => "#"}
            = point.description

%a{"data-icon" => "star", "data-iconpos" => "left", "data-role" => "button", :href => "/map", "data-transition" => "slide", "data-ajax" => "false"}
  Map
%a{"data-icon" => "bars", "data-iconpos" => "left", "data-role" => "button", :href => "/list"}
  List of Places
%a{"data-icon" => "search", "data-iconpos" => "left", "data-role" => "button", :href => "#page1"}
  Search
%a{"data-icon" => "check", "data-iconpos" => "left", "data-role" => "button", :href => "#page1"}
  Log In

app/views/home/map.html.haml
.wrapper{:"data-map" => "true"}
  .tabbable.tabs-left
    %ul.nav.nav-tabs
      %li.active
        %a{"data-toggle" => "tab", :href => "#tab1"} Description
      %li
        %a{"data-toggle" => "tab", :href => "#tab2"} Search
      %li
        %a{"data-toggle" => "tab", :href => "#tab3"} Directions
    .hide-arrow{:onclick => "hide_panel();"}
      %i.icon-chevron-right
    .tab-content
      #tab1.tab-pane.active
        %h5.tab_header
          Full description
        .well.description
          = @desc
      #tab2.tab-pane
        .row-fluid.search_form
          = form_tag("/search", :method => "get", :class => "form-search") do
            .span8
              = text_field_tag(:q, params[:q], :class => "input-medium search-query", :placeholder => "Search")
              = hidden_field_tag(:slider, "slider")
            .span3
              = submit_tag("Search", :class => "btn")
        .row-fluid
          .sapn10.results
            Total points:
            = @size
      #tab3.tab-pane
        #directions-info
          .control-group
            %label.control-label.pointer-label{for:"input-from"}
              %i.icon-map-marker
            .controls
              %input{type:"text", id:"input-from",placeholder:"From"}
          .control-group
            %label.control-label.pointer-label{for:"input-to"}
              %i.icon-map-marker
            .controls
              %input{type:"text", id:"input-to",placeholder:"To"}
        #directions-panel

  .map_section
    - if defined? zoom
      - @zoom = zoom
    - else
      - @zoom = 9

    - center_latitude = (defined? center_lat) ? center_lat : 48.471303
    - center_longitude = (defined? center_long) ? center_long : 22.882928

    #map

= if @q
  :javascript
    show_panel(1);


-# Deprecated Gmap4Rails
-#
-#= gmaps({ "map_options" => {  "auto_adjust" => false,
-#                              "auto_zoom" => true,
-#                              "zoom" => @zoom.to_i,
-#                              "center_latitude" => center_latitude,
-#                              "center_longitude" => center_longitude,
-#                              "do_clustering" => true },
-#          "markers" => {"data" => @json }})


:javascript
  if (document.location.pathname.indexOf("/show_pointer_on_map") == 0){
  $(document).prop('title',"#{raw @desc.to_s}");
  };
  window.markers = #{raw @json.to_json};
  buildMapFromMarkers(window.markers);



-#.well{:style => "margin-top:20px;"}
  .description
    = @desc
    -#Full description...

-##vk_like
-#%script{:type => "text/javascript"}
  VK.Widgets.Like("vk_like", {type: "full"});

app/views/home/map.js.erb
var my_json = <%= raw @json.to_json %>;
buildMapFromMarkers(my_json);

clear_directions_data();

$('.results').text(size);
$('.search_form input.search-query').val(query);
$('#top_search').val(query);

app/views/home/map.mobile.haml
-#=======header===============
- content_for :header do
  %div{"data-role" => "header", "data-theme" => "a"}
    %a.ui-btn-left{"data-icon" => "arrow-l", "data-iconpos" => "left", "data-role" => "button", :href => "/", "data-transition" => "slide", "data-direction" => "reverse"}
      Home
    %a.ui-btn-right{"data-icon" => "gear", "data-iconpos" => "right", "data-role" => "button", :href => "/options", "data-transition" => "slide"}
      Options
    %h3
      Map

-#=======content===============




- if defined? zoom
  - @zoom = zoom
- else
  - @zoom = 9

- center_latitude = (defined? center_lat) ? center_lat : 48.471303
- center_longitude = (defined? center_long) ? center_long : 22.882928

#map_canvas{:style => "position: absolute; left:0; height: -webkit-calc(100% - 45px); height: -moz-calc(100% - 45px); width:100%; top:45px; "}


:javascript

  function GetMarkersFromJSON(url){
    $.getJSON( url, function(data) {
        $.each( data, function(i, marker) {
            $('#map_canvas').gmap('addMarker', {
                'position': new google.maps.LatLng(marker.latitude, marker.longitude),
                'bounds': true
            }).click(function() {
                $('#map_canvas').gmap('openInfoWindow', { 'content': marker.description }, this);
            });
        });        
    });
  }

  $("div:jqmData(role='page'):last").on("pageshow", function() {
          //$('#map_canvas').gmap('refresh');
  });


  $("div:jqmData(role='page'):last").on("pageinit", function() {
       //jQuery('#map_canvas').gmap('addMarker', {'position': '57.7973333,12.0502107', 'bounds': true}).click(function() {
       //      jQuery('#map_canvas').gmap('openInfoWindow', {'content': 'Hello World!'}, this);
       //    });

        //============= Get params from LocalStorage ============================================
          if (localStorage["detect_location"] !== undefined) {
            if (localStorage["detect_location"] == "on")  {
              detect_location = 1
            }
            else {
              detect_location = 0
            }
          } else {
            detect_location = 0
          }

          if (localStorage["radius"] !== undefined) {
            radius = localStorage["radius"]
          } else {
            radius = 0
          }

          opts = {'detect_location': detect_location,
          'radius':radius
          };
        //=======================================================================================


        if (opts.detect_location == 1){
          //============================ My Location ==============================================
          $('#map_canvas').gmap({ 'disableDefaultUI':false, 'callback': function() {
              var self = this;
              self.getCurrentPosition(function(position, status) {
                  if ( status === 'OK' ) {
                      self.set('clientPosition', new google.maps.LatLng(position.coords.latitude, position.coords.longitude));
                      self.addMarker({'position': self.get('clientPosition'), 'bounds': true, 'icon':'http://google-maps-icons.googlecode.com/files/friends.png'});
                      self.addShape('Circle', { 'strokeWeight': 0, 'fillColor': "#008595", 'fillOpacity': 0.25, 'center': self.get('clientPosition'), 'radius': 5, clickable: false });
                      opts.lat = position.coords.latitude;
                      opts.lng = position.coords.longitude;
                      opts.url = function(){if((opts.detect_location == 1)&& (opts.radius !== 0)){return 'pointers.json?radius='+opts.radius+'&lat='+opts.lat+'&lng='+opts.lng}}();
                      GetMarkersFromJSON(opts.url);
                  }
              });
          }});
          //====================================================================================
        }
        else
        {
          $('#map_canvas').gmap().bind('init', function() {
          GetMarkersFromJSON('pointers.json');

          });
        }
  });

app/views/home/options.mobile.haml
-#=======header===============
- content_for :header do
  %div{"data-role" => "header", "data-theme" => "a"}
    %a.ui-btn-left{"data-icon" => "arrow-l", "data-iconpos" => "left", "data-rel" => "back", "data-role" => "button", :href => "/map"}
      Map
    %h3
      Header

-#=======content===============
%div{"data-role" => "fieldcontain"}
  %label{:for => "toggleswitch2"}
    Detect my Position
  %select#detect_location{"data-role" => "slider", "data-theme" => "", :name => "toggleswitch2"}
    %option{:value => "off"}
      Off
    %option{:value => "on"}
      On
%div{"data-role" => "fieldcontain"}
  %label{:for => "slider1"}
    Display Points in Radius (km)
  %input#radius{"data-highlight" => "true", :max => "100", :min => "0", :name => "slider", :type => "range", :value => "50"}/
%a{"data-role" => "button", :href => "#", "onclick" => "save_opts();"}
  Save

:javascript

   // Set switches to saved positions
  $("div:jqmData(role='page'):last").on("pageinit", function() {
    if (localStorage["detect_location"] !== undefined) {
      $( "#detect_location" ).val(localStorage["detect_location"]).slider("refresh");
    };

    if (localStorage["radius"] !== undefined) {
      $('#radius').val(localStorage["radius"]).slider("refresh");
    };
  })

  // Save to Local Storage switches values
  function save_opts(){
    localStorage["detect_location"] = $( "#detect_location" ).val();
    localStorage["radius"] = $( "#radius" ).val();
    window.location.href = "/map";
  }

app/views/home/search.js.erb
var my_json = <%= raw @json.to_json %>;
var size = "Total points: <%= @size %>";
var query = "<%= @q %>";

buildMapFromMarkers(my_json);

$('.results').text(size);
$('.search_form input.search-query').val(query);
$('#top_search').val(query);

show_panel(1);