config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :pointers

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root :to => "home#index"

  get 'map' => 'home#map', :as => 'map'
  get 'list' => 'pointers#list', :as => 'list'
  get '/dynamic_content' => 'pointers#dynamic_content'
  get '/search' => 'home#search'

  get '/parse' => 'pointers#parse', :as => 'parse'
  get 'home/full_desc' => 'home#full_desc'
  get '/my_places' => 'home#my_places'
  get '/get_direction_info' => 'home#get_direction_info'
  get 'show_pointer_on_map/:id' => 'pointers#show_pointer_on_map', :as => 'show_pointer_on_map'
  get 'create_visit/:id' => 'desires#create_visit'
  get 'set_visited/:id' => 'desires#set_visited'
  get 'options' => 'home#options'

  post 'import_ratings' => 'pointers#import_ratings', defaults: {format: :json}
end

app/views/layouts/_google_analytics.haml
:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-49158175-1', 'poi.herokuapp.com');
  ga('send', 'pageview');

app/views/layouts/_message.html.haml
- flash.each do |name, msg|
  %div.fade.in{:class => "alert alert-#{name == :notice ? "success" : "error"}", :style => "display:none;"}
    %a.close{"data-dismiss" => "alert"} &#215;
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/application.html.erb
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">

  <title>Places of Transcarpathia</title>
  <%= Gon::Base.render_data %>
</head>

<body>
<div id="app"></div>
</body>

<%= javascript_pack_tag 'application' %>
<%= stylesheet_pack_tag 'application' %>

</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Places of Transcarpathia
    /[if lt IE 9]
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>

    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"

    = javascript_include_tag '//vk.com/js/api/openapi.js?54'

    %script{:src => "//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry", :type => "text/javascript"}
    %script{:src => "//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js", :type => "text/javascript"}

    %script{:type => "text/javascript"}
      VK.init({apiId: 3164757, onlyWidgets: true});

    = csrf_meta_tags
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}

    = javascript_pack_tag 'application'
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand{:href => root_url}
            Places of Transcarpathia
          .nav-collapse
            %ul.nav
              %li{:class => controller.action_name.in?(["map", "show_pointer_on_map"]) ? "active" : "" }
                = link_to "Map", map_path, :class => 'ajax_map'
              %li{:class => controller.action_name == "all_list" ? "active" : ""}
                = link_to "List", list_path
              - if user_signed_in?
                %li.dropdown
                  %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#", :class => "active"}
                    My places
                    %b.caret
                  %ul.dropdown-menu
                    %li
                      = link_to "I want to visit", "/map?stat=0&my=1", :class => 'ajax_map'
                    %li
                      = link_to "Visited", "/map?stat=1&my=1", :class => 'ajax_map'
                    %li
                      = link_to "All marked", "/map?my=1", :class => 'ajax_map'

              -if user_signed_in? && current_user.is_admin?
                %li
                  = link_to "Parse", parse_path

            = form_tag("/search", :method => "get", :class => "navbar-search pull-left", :id => 'header-search-form',:remote=>true) do
              = text_field_tag(:q, params[:q], :class => "input-medium search-query", :placeholder => "Search", :id=>"top_search")
              = hidden_field_tag(:slider, "", :id => "top_slider")
              %i.icon-remove

            %ul.nav.pull-right
              %li.dropdown
                - if user_signed_in?
                  %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                    = current_user.email
                    %b.caret
                  %ul.dropdown-menu
                    %li
                      = link_to "Profile", edit_user_registration_path
                    %li.divider
                    %li
                      = link_to "Sign out", destroy_user_session_path, :method => :delete
                - else
                  %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                    Please sign in or sign up
                    %b.caret
                  %ul.dropdown-menu
                    %li
                      = link_to "Sign In", new_user_session_path
                    %li.divider
                    %li
                      = link_to "Sign Up", new_registration_path(:user)

    .container
      = render :partial => 'layouts/message'
      .row
        .span12
          = yield
          = yield :scripts

    .counter{:style => "display:none;"}
      /= render :partial => "layouts/counter"
      = render :partial => 'layouts/google_analytics'
    .modal-loader

app/views/layouts/application.mobile.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{:content => "initial-scale=1.0, user-scalable=no", :name => "viewport"}
    %meta{:content => "yes", :name => "apple-mobile-web-app-capable"}
    %meta{:content => "black", :name => "apple-mobile-web-app-status-bar-style"}

    %title Places of Transcarpathia

    %link{:href => "/assets/application_mobile.css", :rel => "stylesheet"}
    %script{:src => "/assets/application_mobile.js"}

    %script{:src => "http://maps.google.com/maps/api/js?sensor=true", :type => "text/javascript"}

  %body
    %div{"data-role" => "page"}
      = yield :header
      %div{"data-role" => "content"}
        = yield
      -#%div{"data-role" => "footer", "data-theme" => "a"}
        %h3
          Footer

    :javascript
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-49158175-1', 'poi.herokuapp.com');
      ga('send', 'pageview');

app/views/layouts/old_application.html.haml
!!!
%html
  %head
    %title Places of Transcarpathia

    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"

    %script{:src => "//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry", :type => "text/javascript"}
    %script{:src => "//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js", :type => "text/javascript"}

    = csrf_meta_tags
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}

    = javascript_pack_tag 'application'
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand{:href => root_url}
            Places of Transcarpathia
          .nav-collapse
            %ul.nav
              %li{:class => controller.action_name.in?(["map", "show_pointer_on_map"]) ? "active" : "" }
                = link_to "Map", map_path, :class => 'ajax_map'
              %li{:class => controller.action_name == "all_list" ? "active" : ""}
                = link_to "List", list_path
              - if user_signed_in?
                %li.dropdown
                  %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#", :class => "active"}
                    My places
                    %b.caret
                  %ul.dropdown-menu
                    %li
                      = link_to "I want to visit", "/map?stat=0&my=1", :class => 'ajax_map'
                    %li
                      = link_to "Visited", "/map?stat=1&my=1", :class => 'ajax_map'
                    %li
                      = link_to "All marked", "/map?my=1", :class => 'ajax_map'

              -if user_signed_in? && current_user.is_admin?
                %li
                  = link_to "Parse", parse_path

            = form_tag("/search", :method => "get", :class => "navbar-search pull-left", :id => 'header-search-form',:remote=>true) do
              = text_field_tag(:q, params[:q], :class => "input-medium search-query", :placeholder => "Search", :id=>"top_search")
              = hidden_field_tag(:slider, "", :id => "top_slider")
              %i.icon-remove

            %ul.nav.pull-right
              %li.dropdown
                - if user_signed_in?
                  %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                    = current_user.email
                    %b.caret
                  %ul.dropdown-menu
                    %li
                      = link_to "Profile", edit_user_registration_path
                    %li.divider
                    %li
                      = link_to "Sign out", destroy_user_session_path, :method => :delete
                - else
                  %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                    Please sign in or sign up
                    %b.caret
                  %ul.dropdown-menu
                    %li
                      = link_to "Sign In", new_user_session_path
                    %li.divider
                    %li
                      = link_to "Sign Up", new_registration_path(:user)

    .container
      = render :partial => 'layouts/message'
      .row
        .span12
          = yield
          = yield :scripts

    .counter{:style => "display:none;"}
      = render :partial => 'layouts/google_analytics'
    .modal-loader